[workspace]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "conserve"
platforms = ["linux-64"]
version = "0.1.0"
conda-pypi-map = { "https://repo.prefix.dev/meta-forge" = "pulumi-mapping.json" }

[tasks]
test = "pytest"

[dependencies]
python = "3.12.*"
pip = "*"
hatchling = "*"
tomlkit = "*"
tyro = "*"
msgspec = "*"
pytest = "*"
deepmerge = "*"
"ruamel.yaml" = "*"
datamodel-code-generator = "*"
packaging = "*"
ipython = "*"
fsspec = "*"
universal-pathlib = "*"
pathvalidate = "*"
aiohttp = "*"
pulumi = "*"
pulumi-sdk-python = "*"
protobuf = "*"

[pypi-dependencies]
conserve = { path = ".", editable = true }
schemastore = "*"
pulumi-github = "*"

[activation.env]
PYTHONDONTWRITEBYTECODE = "1"
PULUMI_BACKEND_URL = "file://."
PULUMI_CONFIG_PASSPHRASE = "passwd"
PULUMI_AUTOMATION_API_SKIP_VERSION_CHECK = "true"
