[workspace]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "conserve"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "pytest"

[dependencies]
python = "3.12.*"
pip = "*"
hatchling = "*"
tomlkit = "*"
tyro = "*"
msgspec = "*"
pytest = "*"
deepmerge = "*"
"ruamel.yaml" = "*"
datamodel-code-generator = "*"
packaging = "*"
ipython = "*"
fsspec = "*"
universal-pathlib = "*"
pathvalidate = "*"
aiohttp = "*"
grpcio = "*"
betterproto2 = "*"

[feature.proto.dependencies]
buf = "*"
betterproto2 = "*"
grpcio = "*"

[feature.proto.tasks]
gen-proto = "buf generate"

[pypi-dependencies]
conserve = { path = ".", editable = true }
schemastore = "*"
packageurl-python = "*"
githubkit = "*"

[activation.env]
PYTHONDONTWRITEBYTECODE = "1"

[environments]
gen = { features = ["proto"] }
