[workspace]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "conserve"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = "*"
hatchling = "*"
tomlkit = "*"
tyro = "*"
msgspec = "*"
pytest = "*"

[pypi-dependencies]
conserve = { path = ".", editable = true }
deepmerge = "*"
